version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: mediahub-postgres
    restart: always
    environment:
      POSTGRES_DB: mediahub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: mediahub-minio
    restart: always
    ports:
      - "9005:9000"  # API: access localhost:9005 for API calls
      - "9006:9001"  # Console: access localhost:9006 for MinIO Console navigation
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mediahub-api:
    build: .
    container_name: mediahub-api
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # JWT
      JWT_SECRET: my-super-secret-key-which-is-at-least-32-bytes
      JWT_EXPIRATION: 300000
      JWT_REFRESH_EXPIRATION: 900000

      # DATABASE
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediahub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

      # MINIO
      MINIO_URL: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9005
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: media-covers

    ports:
      - "8081:8081"


volumes:
  postgres_data:
  minio_data: