server:
    port: 8080

spring:
    application:
        name: mediahub-api

    datasource:
        url: jdbc:postgresql://postgres:5432/mediahub
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: true
        locations: classpath:db/migration

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB

# JWT
security:
    jwt:
        secret: my-super-secret-key-which-is-at-least-32-bytes
        expiration: 300000 # 5 minutes em ms
        refresh-expiration: 900000 # 15 minutes

#  MinIO
minio:
    url: http://minio:9000
    public-url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: media-covers
